# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: "Allo Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # This job runs on Linux
    runs-on: [self-hosted, aie, xdna1]
    container:
      image: chhzh123/allo:latest
      options: > 
        -v /opt:/host-opt:ro
    steps:
    # https://github.com/actions/checkout/issues/363#issuecomment-1915075699
    - name: Install git in container
      run: |
        apt-get -y install git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    - name: Build Allo
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pip install -v -e .
    - name: AIE unit tests
      shell: bash
      run: |
        source activate allo
        python3 -m pip install mlir_aie -f https://github.com/Xilinx/mlir-aie/releases/expanded_assets/v1.0
        python3 -m pip install https://github.com/Xilinx/llvm-aie/releases/download/nightly/llvm_aie-19.0.0.2025041501+b2a279c1-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
        source scripts/aie-setup.sh --clone-dir externals/
        source /host-opt/common/setupVitis.sh
        source /host-opt/common/setupXRT.sh
        export MLIR_AIE_EXTERNAL_KERNEL_DIR=${PWD}/externals/mlir-aie/aie_kernels/
        export RUNTIME_LIB_DIR=${PWD}/externals/mlir-aie/runtime_lib/
        export PATH=/root/llvm-project/build/bin:${PATH}
        export LLVM_BUILD_DIR=/root/llvm-project/build
        export OMP_NUM_THREADS=128
        python3 -m pytest tests/dataflow/aie -v
        unset OMP_NUM_THREADS
    - name: Formatting Check
      shell: bash
      run: |
        source activate allo
        bash scripts/lint/task_lint.sh
    - name: Unit tests
      shell: bash
      run: |
        source activate allo
        export PATH=/root/llvm-project/build/bin:${PATH}
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pytest --ignore=tests/dataflow tests -v
        export OMP_NUM_THREADS=128
        python3 -m pytest --ignore=tests/dataflow/aie tests/dataflow -v
        unset OMP_NUM_THREADS
    - name: Tutorial
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pytest tutorials -v
    - name: Benchmark
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pytest examples/polybench -v
    - name: PyTorch
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pip install torch==2.5.1
        python3 examples/torch/toy.py
        python3 examples/torch/mlp.py
