# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: "Allo Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # This job runs on Linux
    runs-on: [self-hosted, aie, xdna1]
    container:
      image: chhzh123/allo:latest
      options: "-v /opt:/host-opt:ro -v /home/sf668/usr/mlir-aie:/mlir-aie:ro"
    steps:
    # https://github.com/actions/checkout/issues/363#issuecomment-1915075699
    - name: Install git in container
      run: |
        apt-get -y install git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    - name: Build Allo
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pip install -v -e .
    - name: AIE unit tests
      shell: bash
      run: |
        source activate allo
        python3 -m pip install mlir_aie -f https://github.com/Xilinx/mlir-aie/releases/expanded_assets/v1.0
        python3 -m pip install https://github.com/Xilinx/llvm-aie/releases/download/nightly/llvm_aie-19.0.0.2025041501+b2a279c1-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
        python3 -m pip install -r /mlir-aie/python/requirements.txt
        HOST_MLIR_PYTHON_PACKAGE_PREFIX=aie python3 -m pip install -r /mlir-aie/python/requirements_extras.txt
        python3 -m pip install -r /mlir-aie/python/requirements_ml.txt
        export MLIR_AIE_INSTALL_DIR="$(pip show mlir_aie 2>/dev/null | grep ^Location: | awk '{print $2}')/mlir_aie"
        export PEANO_INSTALL_DIR="$(pip show llvm-aie 2>/dev/null | grep ^Location: | awk '{print $2}')/llvm-aie"
        export PATH=${MLIR_AIE_INSTALL_DIR}/bin:${PATH} 
        export PYTHONPATH=${MLIR_AIE_INSTALL_DIR}/python:${PYTHONPATH}
        export LD_LIBRARY_PATH=${MLIR_AIE_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
        export INSTALL_PY_MAIN="$MLIR_AIE_INSTALL_DIR/python/aie/compiler/aiecc/main.py"
        cp /mlir-aie/python/compiler/aiecc/main.py "$INSTALL_PY_MAIN"
        source /host-opt/common/setupVitis.sh
        source /host-opt/common/setupXRT.sh
        export MLIR_AIE_EXTERNAL_KERNEL_DIR=/mlir-aie/aie_kernels/
        export RUNTIME_LIB_DIR=/mlir-aie/runtime_lib/
        export PATH=/root/llvm-project/build/bin:${PATH}
        export LLVM_BUILD_DIR=/root/llvm-project/build
        export OMP_NUM_THREADS=128
        python3 -m pytest tests/dataflow/aie -v
        unset OMP_NUM_THREADS
    - name: Formatting Check
      shell: bash
      run: |
        source activate allo
        bash scripts/lint/task_lint.sh
    - name: Unit tests
      shell: bash
      run: |
        source activate allo
        export PATH=/root/llvm-project/build/bin:${PATH}
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pytest --ignore=tests/dataflow tests -v
        export OMP_NUM_THREADS=128
        python3 -m pytest --ignore=tests/dataflow/aie tests/dataflow -v
        unset OMP_NUM_THREADS
    - name: Tutorial
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pytest tutorials -v
    - name: Benchmark
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pytest examples/polybench -v
    - name: PyTorch
      shell: bash
      run: |
        source activate allo
        export LLVM_BUILD_DIR=/root/llvm-project/build
        python3 -m pip install torch==2.5.1
        python3 examples/torch/toy.py
        python3 examples/torch/mlp.py
